### ISSUE TITLE
Decimal separator incorrect for US

### ISSUE THREAD

**Issue by mickeysoft42** [sweitzel/Biet-O-Matic-BE#21]
It looks like the decimal separator is not internationalized.

I'm in the US using the US version of eBay.

Here I entered an amount of $220 in Bid-O-Matic:

![image](https://user-images.githubusercontent.com/75404571/100957046-a3be5800-34ce-11eb-9630-47078cc4382c.png)

Here's what happens on the auction page:

![image](https://user-images.githubusercontent.com/75404571/100957118-bc2e7280-34ce-11eb-8ef0-d5ceea913084.png)

As you can see, the number entered is 220,00, but should be 220.00 instead.

**Comment by sweitzel** [comment]
I'll have to check this one out, and will of course fix this if I am able to reproduce.

**Comment by sweitzel** [comment]
@mickeysoft42 should be fixed with 0.5.3 - can you confirm?

**Comment by rdratlos** [comment]
I can confirm it working with 0.5.4 on Firefox but the issue is a little bit tricky:
When configuring BOM to force ebay.de the decimal separator setting is not fixed. Instead it depends on the language settings of the browser:
Here is the bid overview screenshot for browser language set to en-US:
![Screenshot_Firefox_enUS](https://user-images.githubusercontent.com/6354353/104122932-61e3c580-5348-11eb-8c31-8a52172f5aaf.jpg)
And below you find a screenshot after changing the browser language to de-DE.
![Screenshot_Firefox_deDE](https://user-images.githubusercontent.com/6354353/104122956-8b9cec80-5348-11eb-8ccc-1e4e7d593415.jpg)

Ebay does not care about the language settings of the browser for choosing the decimal separator.. Current offer always uses a German decimal separator. 

Maybe we should at least document this in the manual. Haven't tested it for Chrome, yet.

**Comment by rdratlos** [comment]
Below a screenshot when using ebay.com with German language settings in Firefox:
![Screenshot_EbayCom_Firefox_deDE](https://user-images.githubusercontent.com/6354353/104123259-5beee400-534a-11eb-8563-fd87bd8b38a0.jpg)

As soon as I switch to en-US language settings in Firefox the decimal separator is correct again.

**Comment by sweitzel** [comment]
Closed - decimal separators work now as expected.
The selected browser language influences the language setting used by BE and of the decimal separator format.
